openapi: 3.0.1
info:
  title: GPT WebBuilder Template Agent
  version: "1.0"
paths:
  /fetch-template:
    get:
      summary: Fetch a template or snippet from the web
      parameters:
        - name: q
          in: query
          required: true
          description: The template search term
          schema:
            type: string
      responses:
        '200':
          description: Template result
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  result:
                    type: string
